language: node_js
node_js:
- '0.12'
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - DEPLOY_BRANCH=master
  - BLUEHOST_USER=ranking5
  - BLUEHOST_PATH=rankingdigitalrights.org:public_html/index2017
  - secure: eT8hFYLdJMN2fFuK06VkpPNcs1+wRs/eg6NgYheonryMp4mT7J7RFkfBQkGeqIQwfPpPLN2HtARCGXk32d3OCR22qFHNEVOTEtqet+pZUbDWkiQcFBHYSHBTPECsmivPQsTj2mohH66AN9XMDavaw0cpawKdEJ63A9xffqgHz5O4AaJIo5GdBK6e59rTRfD3MkMgXqzTEH5ZfmqMWWaGX46ZCR0L/GP1XAp/5Dp6nGMyXpiFrSt8qOrHwga1x3mlZHHg1FD9DOE+PiCqTrS8ulx/zQwjJMXr4K2K639kNiH2brxtgolFyFc5apumssmnjdqZMjks9JHppqbT6R3FP/GlpYjpbmoBI+RLQR88qqQyNQE3bCccblDQG4yPdrMDOGzt/XWZANxprfMS3Z6Q0uNeactXLgPStfb1DxmWPS+mpXWY+fkpFeF5ISUFBU44Ip3155y2mf6SevcEf88FkkIlAcLUfGeQ40S8pr1LD9ScqzUxg+yH3mEammxZW4JD5x4eopR7CbW5r3Ng1m8u3+/bVS+rJtoJqw8+oDOicRb8seA8fcpeH0kAjyomZNM6TGC4d43WXCKeYfmEdW+5XDAl8KALXWKIL4XSMMZEyDBXIKmN+s5eQLs7y0qY/jbSDNqadMz2JWbF7SkQrEXuLLaudC5nKZCoWbGcjk4RuEA=
cache:
  directories:
  - node_modules
  - bundle/cache
before_install:
- openssl aes-256-cbc -k "$rdr" -in rdr.enc -out rdr -d
- chmod 400 rdr
- chmod +x ./.build_scripts/deploy.sh
- chmod +x ./.build_scripts/build.sh
script:
- "./.build_scripts/build.sh"
after_success:
- "./.build_scripts/deploy.sh"
