language: node_js
node_js:
- '0.12'
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - DEPLOY_BRANCH=master
  - BLUEHOST_USER=ranking5
  - BLUEHOST_PATH=rankingdigitalrights.org:public_html/index2017
  - secure: Q3860WD7PTOubMc7lNu5f2hJcFA9ezL4ZtqGmu9F/dECzZzEZ7ES+YYELSlVNv2YKNmVCWxIS50uQIxWEEx9LJnJ9SUROsJ0/KffnQUTy4ZC6zvOAJPrwuguSa0h3AvtCWVR1shCfspcifNvSvh5dgvZDXYOfkOUjBo/GebV472Fz+/4STwpZeS0jQFo3aombe1nLxfzWmDYoYvqe7oNfm7AshkCY7QRRMBlAWMDwiEqinQaD8jO2jnfOG33fZn0cnpY3IADteunY4o1AAaIw7bCLe2smqdKgbYkeoN3vGSsws4qEVOao46nb0hkIGX+y0CkyQJFBtVlCgAjF/omRu8SWX+4stXqU15HjTP7hYVkGmdY/S0FOP7nBdEh+Uu+KxA4T0Il8PjkTTi27CczRk/pizi1RsRvADUZ6P9y1RCfahKVPVTK42iAfwm/4BEvrjBVk9MrY2O/dp752RFx9fJEdFkGuzpVWH/ieW8ypUxmssyuMHNM7XCSRsJEGAn0D6CT4VJunUZWq873fH2iB+Lp71mVbUm0Q8u+hmrLU7rXsefotwP9MXEV1FgKwXw8aEvNa+k5dsu1dgqrQuKqoMoP/Afq4lsXsg7VUC575zQtzMpntjWPVxcPtNNyGWzpEqNEb85i7+p7cptkBDgQ98BTJRPzne1rLWfJONX2D/8=
cache:
  directories:
  - node_modules
  - bundle/cache
before_install:
- openssl aes-256-cbc -k "$secure" -in rdr.enc -out rdr -d
- chmod 400 rdr
- chmod +x ./.build_scripts/deploy.sh
- chmod +x ./.build_scripts/build.sh
script:
- "./.build_scripts/build.sh"
after_success:
- "./.build_scripts/deploy.sh"
